### PR TITLE
Add Paired Single Move Tests

### PR DESCRIPTION
**Pull request by Geotale**
Adds a new file for common float tests -- This will likely be used more in the future as well
Modifies two other test files which now use functions in the CommonFloat file
The location of `frsqrte_expected` might change because it's not exactly common? ^^;
Adds software implementation of mantissa truncation and rounding given the expected rounding mode
Both of these are for tests for float move instructions
These instructions include:
ps_merge, ps_mr, ps_neg, ps_abs, ps_nabs
ps_rsqrte is included to check for a similar quirk (it returns an f64)
Marked as a draft until I or someone else can test on hardware (so like. a few hours if I can get it working)

### CODE REVIEW

**Comment by Geotale** [comment]
I still haven't been able to get `wiiload` to work, but on Dolphin at least the number of failed tests is equivalent regardless of the version I tested with, so it should work?
I should also probably recheck `fres` tests since that was largely modified
I'm sorry for the kinda large changes, I rewrote the function using what my own implementation did then fixed from there because I didn't really know what to do with Dolphin's ^^;
Either way, this should hopefully be enough for an open review for more fixes :D

**Comment by Pokechu22** [comment]
> I still haven't been able to get wiiload to work

In my experience, wiiload over wi-fi can sometimes be unreliable (but I think this does depend on your access point hardware). If you use a wired ethernet/USB connection (for the Wii, though your PC can be wireless still) it's much more stable.

> but on Dolphin at least the number of failed tests is equivalent regardless of the version I tested with, so it should work?

Are you checking different versions of hwtests, or different versions of Dolphin? It'd be useful to make that some of the tests fail before your PR (https://github.com/dolphin-emu/dolphin/pull/13059) and pass with the PR.

**Comment by Geotale** [comment]
I'm sorry I forgot to update on that, I did get it resolved ^^ It was 5g vs 2.4g wifi!! When connecting to the same network it worked """perfectly""" (sometimes it just got stuck for some reason and I'd have to restart my entire Wii U via unplug and plug back in -> VWii, but this is apparently a common occurrence for some reason), which is what I used to verify all tests worked in the end :>

**Comment by Tilka** [comment]
Cross-checked that fctiw/pairedmove/reciprocal pass on a real Wii.

**Pull request merged**
